//*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
package perpustakaan;

import java.awt.HeadlessException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JustineSun
 */
public class perpustakaan extends javax.swing.JFrame {

//    private Connection con;
//    private Statement stat;
//    private ResultSet res;
    
    public Statement stat;
    public ResultSet res;
    Connection con = ConnectDB.connect();

    public perpustakaan() {
        initComponents();
        setVisible(true);
//        koneksi();
        kosongkan();
        ClearTabel();
    }

    private void tabel() throws SQLException {
        Statement stat = con.createStatement();
        ResultSet res = stat.executeQuery("SELECT * FROM library");
        
        DefaultTableModel tb = new DefaultTableModel();
        // Memberi nama pada setiap kolom tabel
        tb.addColumn("NoBuku");
        tb.addColumn("JudulBuku");
        tb.addColumn("Author");
        tb.addColumn("Tahun");
        tb.addColumn("Publisher");
        tb.addColumn("Eksemplar");
        tabel.setModel(tb);
        
        
     
        while(res.next()) {
                Object[] data = {
                    res.getString("NoBuku"),
                    res.getString("JudulBuku"),
                    res.getString("Author"),
                    res.getString("Tahun"),
                    res.getString("Publisher"),
                    res.getString("Eksemplar")
                };
                // Tambah baris dengan data dari database 
                tb.addRow(data);
                tabel.setModel(tb);  
            }
    }
    
    private void kosongkan() {
        no.setText("");
        judul.setText("");
        pengarang.setText("");
        tahun.setText("");
        penerbit.setText("");
        eksemplar.setText("");
        no.requestFocus();
    }

    private void ClearTabel() {
        int cb = tabel.getRowCount();
        int cc = tabel.getColumnCount();
        for (int i = 0; i < cb; i++) {
            for (int j = 0; j < cc; j++) {
                tabel.setValueAt(null, i, j);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        judul = new javax.swing.JTextField();
        pengarang = new javax.swing.JTextField();
        tahun = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        baca_tabel = new javax.swing.JButton();
        clear_tabel = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        eksemplar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan");
        setBackground(new java.awt.Color(242, 183, 213));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 178, 195));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel1.setText("Input Data Buku Library");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 200, 20));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("No. Buku");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Judul Buku");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Author");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Tahun");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 20));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Publisher");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 60, 20));

        no.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        no.setForeground(new java.awt.Color(102, 102, 102));
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 60, -1));

        judul.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        judul.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 390, 50));

        pengarang.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pengarang.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 300, -1));

        tahun.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tahun.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 70, -1));

        penerbit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        penerbit.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 164, -1));

        simpan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        simpan.setForeground(new java.awt.Color(51, 51, 51));
        simpan.setText("Save");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 91, -1));

        edit.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        edit.setForeground(new java.awt.Color(51, 51, 51));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 91, -1));

        baca_tabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        baca_tabel.setForeground(new java.awt.Color(51, 51, 51));
        baca_tabel.setText("Read Tabel");
        baca_tabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baca_tabelActionPerformed(evt);
            }
        });
        getContentPane().add(baca_tabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        clear_tabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        clear_tabel.setForeground(new java.awt.Color(51, 51, 51));
        clear_tabel.setText("Clear Tabel");
        clear_tabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_tabelActionPerformed(evt);
            }
        });
        getContentPane().add(clear_tabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        hapus.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(51, 51, 51));
        hapus.setText("Delete");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 91, -1));

        keluar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        keluar.setForeground(new java.awt.Color(51, 51, 51));
        keluar.setText("Close");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 91, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No. Buku", "Judul Buku", "Author", "Tahun", "Publisher", "Eksemplar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 590, 180));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel9.setText("Eksemplar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 70, 20));

        eksemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eksemplarActionPerformed(evt);
            }
        });
        getContentPane().add(eksemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 80, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\maxresdefault.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 600));

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 630, 200));

        setSize(new java.awt.Dimension(658, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed

        int jawab = JOptionPane.showConfirmDialog(null, "Data ini akan dihapus, lanjutkan ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (jawab == 0) {
            try {
                stat = con.createStatement();
                String query = "DELETE FROM library WHERE nobuku= '" + no.getText() + "'";
                stat.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                kosongkan();
                tabel();  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void clear_tabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_tabelActionPerformed
        ClearTabel();
    }//GEN-LAST:event_clear_tabelActionPerformed

    private void baca_tabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baca_tabelActionPerformed
        try {
            tabel();
        } catch (SQLException ex) {
            Logger.getLogger(perpustakaan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_baca_tabelActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            if(no.getText().equals("") || judul.getText().equals("") || pengarang.getText().equals("") || tahun.getText().equals("") || penerbit.getText().equals("") || eksemplar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi data dengan lengkap");
            return;
            }
            
            Statement stat = con.createStatement();
            

            String query = "UPDATE library SET judulbuku=?,author=?,tahun=?,publisher=?,eksemplar=? WHERE nobuku=?";
            
            // Buat mysql insert preparedstatement
            PreparedStatement preparedStmt = con.prepareStatement(query);
            preparedStmt.setString   (1, judul.getText());
            preparedStmt.setString   (2, pengarang.getText());
            preparedStmt.setString   (3, tahun.getText());
            preparedStmt.setString   (4, penerbit.getText());
            preparedStmt.setString   (5, eksemplar.getText());
            preparedStmt.setString   (6, no.getText());
           
            // Eksekusi preparedstatement
            preparedStmt.execute();
            
            kosongkan();
            tabel();
            JOptionPane.showMessageDialog(rootPane, "Data berhasil Diupdate");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_editActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try {       
            if(no.getText().equals("") || judul.getText().equals("") || pengarang.getText().equals("") || tahun.getText().equals("") || penerbit.getText().equals("") || eksemplar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi data dengan lengkap");
            return;
            }
            
            
            // Persiapkan string query
            String query = "INSERT INTO library " +" values (?,?,?,?,?,?)";
            PreparedStatement preparedStmt = con.prepareStatement(query);
            preparedStmt.setString (1, no.getText());
            preparedStmt.setString   (2, judul.getText());
            preparedStmt.setString   (3, pengarang.getText());
            preparedStmt.setString   (4, tahun.getText());
            preparedStmt.setString   (5, penerbit.getText());
            preparedStmt.setString   (6, eksemplar.getText());
            
            
            // Eksekusi preparedstatement
            preparedStmt.execute();
            
            
            kosongkan();//Mengosongkan text field setelah berhasil menyimpan data
            tabel();// Menampilkan isi tabel
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan...");
      
            // Tutup koneksi
//            con.close();          
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        try {
            //melakukan pencarian data berdasarkan primary key pada tabel
            res = stat.executeQuery("select * from library where " + "NoBuku='" + no.getText() + "'"
            );

            while (res.next()) {
                judul.setText(res.getString("JudulBuku"));
                pengarang.setText(res.getString("Author"));
                tahun.setText(res.getString("Tahun"));
                penerbit.setText(res.getString("Publisher"));
                eksemplar.setText(res.getString("Eksemplar"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_noActionPerformed

    private void eksemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eksemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eksemplarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baca_tabel;
    private javax.swing.JButton clear_tabel;
    private javax.swing.JButton edit;
    private javax.swing.JTextField eksemplar;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judul;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField no;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField pengarang;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tahun;
    // End of variables declaration//GEN-END:variables

    private static class Eksemplar {


        public Eksemplar() {
        }
    }
}
